config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  resources :chatrooms
  resources :private_chats, only: [:create, :show]
  resources :messages, only: :create
  get 'chatroom/:id' => 'chatrooms#check_password', as: :chatroom_locked
  post 'chatroom/:id' => 'chatrooms#show_with_password', as: :check_chatroom_password
  get 'chatroom/:id/editpassword' => 'chatrooms#edit_password', as: :edit_chatroom_password
  put 'chatroom/:id/editpassword' => 'chatrooms#update_password', as: :update_chatroom_password
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'chatrooms#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.present?
      can :read, :all
      can :destroy, Chatroom, user_id: user.id
      can :update, Chatroom, user_id: user.id
      can :edit_password, Chatroom, user_id: user.id
      can :update_password, Chatroom, user_id: user.id
      can :check_password, Chatroom
      can :show_with_password, Chatroom
      can :create, Chatroom
      can :private_message, Chatroom
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_secure_password validations: false
  # has_secure_password validations: true, on: :update_password

  has_many :messages, as: :chat, dependent: :destroy
  has_many :users, through: :messages

  belongs_to :user

  validates :topic, presence: true, uniqueness: true, case_sensitive: false
  validates :password, length: { minimum: 6 }, unless: :skip_password_validation, on: :create

  private

  def skip_password_validation
    puts !is_private
    !is_private
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chat, polymorphic: true
  belongs_to :user
end

app/models/private_chat.rb
class PrivateChat < ApplicationRecord
  belongs_to :user_one, class_name: 'User'
  belongs_to :user_two, class_name: 'User'

  has_many :messages, as: :chat, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :messages, as: :chat
  has_many :chatrooms, through: :messages, source: :chat, source_type: "Chatroom"
  has_many :private_chats, through: :messages, source: :chat, source_type: "PrivateChat"
  devise :database_authenticatable, :registerable,
    :trackable, :validatable

  devise :omniauthable, :omniauth_providers => [:facebook]


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include DeviseHelper
  
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  layout :layout_by_resource

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email])
  end

  def layout_by_resource
    if devise_controller?
      "devise"
    else
      "application"
    end
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  load_and_authorize_resource

  before_action :set_chatroom, only: [:show, :check_password, :show_with_password, :destroy, :edit, :update, :edit_password, :update_password]

  respond_to :html
  respond_to :js, only: [:check_password, :edit, :edit_password]

  def index
    @chatrooms = Chatroom.all
  end

  def new
    @chatroom = Chatroom.new
  end

  def show
    @message = Message.new
  end

  def edit
  end

  def edit_password
  end

  def update
    @chatroom.assign_attributes(chatroom_params)
    @chatroom.topic.gsub!(' ','_').downcase! if @chatroom.topic.include?(' ')
    if @chatroom.save
      flash[:notice] = 'Chatroom updated successfully'
      respond_with(@chatroom)
    end
  end

  def update_password
    if @chatroom.authenticate(params[:old_password])
      if @chatroom.update_attributes(change_chatroom_password_params)
        redirect_to @chatroom, flash: { notice: "Chatroom password changed successfully" }
      else
        redirect_to @chatroom, flash: { alert: "Passwords does not match." }
      end
    else
      redirect_to @chatroom, flash: { alert: "Password Incorrect." }
    end
  end

  def check_password
  end

  def show_with_password
    if @chatroom.authenticate(params[:password])
      session[:chatroom_access] = @chatroom.id
      redirect_to chatroom_path(@chatroom)
    else
      session[:chatroom_access] = nil
      redirect_to :back, flash: { alert: 'Incorrect password' }
    end
  end

  def create
    @chatroom = Chatroom.new(chatroom_params)
    @chatroom.topic.gsub!(' ','_').downcase! if @chatroom.topic.include?(' ')
    @chatroom.user = current_user
    if @chatroom.save
      ActionCable.server.broadcast 'chatgroups',
        channel: @chatroom.topic,
        id: @chatroom.id,
        user_count: @chatroom.users.uniq.count,
        lock: @chatroom.is_private?
      redirect_to root_path
    else
      flash[:error] = @chatroom.errors.full_messages.join(',')
      render :new
    end
  end

  def destroy
    redirect_to root_path, flash: { notice: "Chatroom ##{@chatroom.topic} is successfully deleted." } if @chatroom.destroy
  end

  private

  def set_chatroom
    @chatroom = Chatroom.find(params[:id].to_i)
  end

  def chatroom_params
    params.require(:chatroom).permit(:topic, :is_private, :password)
  end

  def change_chatroom_password_params
    params.require(:chatroom).permit(:password, :password_confirmation)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    message = Message.new(message_params)
    message.user = current_user
    if message.save
      ActionCable.server.broadcast 'messages',
        message: message.body,
        user: message.user.name,
        topic: (message.chat_type == "Chatroom" ? message.chat.topic : message.chat.id),
        user_id: message.user.id
      head :ok
    else
      redirect_to chatrooms_path
    end
  end

  private

  def message_params
    params.require(:message).permit(:body, :chat_id, :chat_type)
  end
end

app/controllers/private_chats_controller.rb
class PrivateChatsController < ApplicationController
  def show
    @recipient = User.find(params[:id])

    if @chatroom = PrivateChat.where(user_one: current_user).presence
      @chatroom = @chatroom.where(user_two: @recipient).first
    elsif @chatroom = PrivateChat.where(user_two: current_user).presence
      @chatroom = @chatroom.where(user_one: @recipient).first
    else 
      @chatroom = PrivateChat.create(user_one: current_user, user_two: @recipient)
    end
    
    @message = Message.new

    render 'chatrooms/show'
  end

  def create
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
  def chatroom_lock_or_unlocked_path(chatroom)
    Chatroom.find(chatroom).is_private? ? chatroom_locked_path(chatroom) : chatroom_path(chatroom)
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" unless devise_error_messages?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    # sentence = I18n.t("errors.messages.not_saved",
    #                   :count => resource.errors.count,
    #                   :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation">
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    !resource.errors.empty?
  end

end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/private_chats_helper.rb
module PrivateChatsHelper
end

app/views/chatrooms/_close_chatroom.html.erb
<h2 class="text-center">Chatroom is LOCKED</h2>
<h1 class="text-center">
  <%= icon('lock',nil, style: 'font-size: 90px;') %>
</h1>
<div class="text-center">
  <%= link_to 'Enter Password', chatroom_locked_path, class: 'btn btn-primary btn-lg', remote: true %>
</div>

app/views/chatrooms/_edit.erb
<div class="modal fade" id="edit_chatroom_modal" tabindex='-1' role='dialog' aria-labelledby='chatroom_modal'>
  <div class="modal-dialog" role='document'>
    <div class="modal-content">
      <div class="modal-header">
        <button type='button' class='close' data-dismiss='modal' aria-label='close'>
          <span aria-hidden='true'>&times;</span>
        </button>
        <h4 class="modal-title">Rename #<%= @chatroom.topic %> chatroom</h4>
      </div>
      <%= form_for(@chatroom, url: chatroom_path(@chatroom), method: :put) do |f| %>
        <div class="modal-body">
          <div class="form-group">
            <%= f.text_field :topic, class: 'form-control', placeholder: 'Enter update chatroom name' %>
          </div>
        </div>
        <div class="modal-footer">
          <button type='button' class='btn btn-default btn-sm' data-dismiss='modal'>Cancel</button>
          <%= submit_tag 'Update Chatroom', class: 'btn btn-primary btn-sm' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/chatrooms/_edit.html.erb
<div class="modal fade" id="edit_chatroom_modal" tabindex='-1' role='dialog' aria-labelledby='chatroom_modal'>
  <div class="modal-dialog" role='document'>
    <div class="modal-content">
      <div class="modal-header">
        <button type='button' class='close' data-dismiss='modal' aria-label='close'>
          <span aria-hidden='true'>&times;</span>
        </button>
        <h4 class="modal-title">Rename #<%= @chatroom.topic %> chatroom</h4>
      </div>
      <%= form_for(@chatroom, url: chatroom_path(@chatroom), method: :put) do |f| %>
        <div class="modal-body">
          <div class="form-group">
            <%= f.text_field :topic, class: 'form-control', placeholder: 'Enter update chatroom name' %>
          </div>
        </div>
        <div class="modal-footer">
          <button type='button' class='btn btn-default btn-sm' data-dismiss='modal'>Cancel</button>
          <%= submit_tag 'Update Chatroom', class: 'btn btn-primary btn-sm' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/chatrooms/_edit_password.html.erb
<div class="modal fade" id="edit_chatroom_password_modal" tabindex='-1' role='dialog' aria-labelledby='chatroom_modal'>
  <div class="modal-dialog modal-sm" role='document'>
    <div class="modal-content">
      <div class="modal-header">
        <button type='button' class='close' data-dismiss='modal' aria-label='close'>
          <span aria-hidden='true'>&times;</span>
        </button>
        <h4 class="modal-title">Change Password</h4>
      </div>
      <%= form_for(@chatroom, url: edit_chatroom_password_path(@chatroom), method: :put) do |f| %>
        <div class="modal-body">
          <div class="form-group">
            <%= password_field_tag "old_password", nil, class: 'form-control', placeholder: 'Enter Old Password'  %>
          </div>
          <div class="form-group">
            <%= f.password_field :password, class: 'form-control', placeholder: 'Enter New Password'  %>
          </div>
          <div class="form-group">
            <%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'Re-enter New Password'  %>
          </div>
        </div>
        <div class="modal-footer">
          <button type='button' class='btn btn-default btn-sm' data-dismiss='modal'>Cancel</button>
          <%= submit_tag 'Update Chatroom', class: 'btn btn-primary btn-sm' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/chatrooms/_modal_locked_chatroom.html.erb
<div class="modal fade" id="chatroom_modal" tabindex='-1' role='dialog' aria-labelledby='chatroom_modal'>
  <div class="modal-dialog modal-sm" role='document'>
    <div class="modal-content">
      <div class="modal-header">
        <button type='button' class='close' data-dismiss='modal' aria-label='close'>
          <span aria-hidden='true'>&times;</span>
        </button>
        <h4 class="modal-title">#<%= chatroom.topic %> is locked</h4>
      </div>
      <%= form_tag check_chatroom_password_path(chatroom) do %>
        <div class="modal-body">
          <div class="form-group">
            <%= password_field_tag :password, nil, class: 'form-control', placeholder: 'Enter Password' %>
          </div>
        </div>
        <div class="modal-footer">
          <button type='button' class='btn btn-default btn-sm' data-dismiss='modal'>Cancel</button>
          <%= submit_tag 'Go', class: 'btn btn-primary btn-sm' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/chatrooms/_open_chatroom.html.erb
<div class="clearfix">
  <h4 class="text-muted">#<%= chatroom.class == Chatroom ? chatroom.topic : @recipient.name %></h4>
  <% if can? :destroy, chatroom %>
    <h4>
      <% if chatroom.is_private? %>
        <%= link_to "#{icon('lock', 'Change Password')}".html_safe, edit_chatroom_password_path(chatroom), class: 'btn btn-warning btn-xs', remote: true %>
      <% end %>
      <%= link_to "#{icon('pencil-square-o', 'Rename')}".html_safe, edit_chatroom_path(chatroom), class: 'btn btn-info btn-xs', remote: true %>
      <%= link_to "#{icon('trash-o', 'Delete')}".html_safe, chatroom_path(chatroom), method: :delete, class: 'btn btn-danger btn-xs', data: { confirm: "Are you sure you want to delete #{chatroom.topic} chatroom?"} %>
    </h4>
  <% end %>
</div>

<div class="panel panel-default">
  <% if chatroom.try(:messages).try(:any?) %>
    <div class="panel-body messages" id="messages_<%= chatroom.class == Chatroom ? chatroom.topic : chatroom.id %>">
      <%= render partial: 'messages/message', collection: chatroom.messages.sort, as: :message %>
    </div>
  <% else %>
    <div class="panel-body hidden messages" id="messages_<%= chatroom.class == Chatroom ? chatroom.topic : chatroom.id %>">
    </div>
  <% end %>
</div>
<%= render partial: 'messages/message_form', locals: { message: message, chatroom: chatroom } %>

app/views/chatrooms/check_password.js.erb
$('#show_modal').html("<%= j render partial: 'modal_locked_chatroom', locals: {chatroom: @chatroom} %>");
$('#chatroom_modal').modal();
$('#chatroom_modal').on('shown.bs.modal', function() {
  $('#password').focus();
})

app/views/chatrooms/create.html.erb
<h1>Chatrooms#create</h1>
<p>Find me in app/views/chatrooms/create.html.erb</p>

app/views/chatrooms/edit.js.erb
$('#show_modal').html("<%= j render 'edit' %>");
$('#edit_chatroom_modal').modal();

app/views/chatrooms/edit_password.js.erb
$('#show_modal').html("<%= j render 'edit_password' %>");
$('#edit_chatroom_password_modal').modal();

app/views/chatrooms/index.html.erb
<div class="col-md-6">
  <div class="well">
    <h3 class="text-center">Chatrooms</h3>
    <div class="row">
      <div id="all_channels">
        <% @chatrooms.each do |chatroom| %>
          <div class="col-xs-12" style="margin-bottom: 5px;">
            <%= link_to chatroom_lock_or_unlocked_path(chatroom), class: 'btn btn-primary', style: 'width: 100%;', remote: chatroom.is_private? do %>
              <div class="clearfix">
                <span class="pull-left"><%= "##{chatroom.topic} ( #{chatroom.users.uniq.count} #{icon('user')} )".html_safe %></span>
                <span class="pull-right"><%= icon('lock') if chatroom.is_private? %></span>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="col-xs-12">
        <%= link_to 'Create Channel', new_chatroom_path, class: 'btn btn-success', style: 'width: 100%;' %>
      </div>
    </div>
  </div>
</div>

<div class="col-md-6">
  <div class="well">
    <h3 class="text-center">PM Users</h3>
    <div class="row">
      <% User.where.not(id: current_user.id).each do |user| %>
        <div class="col-xs-12" style="margin-bottom: 5px;">
          <%= link_to private_chat_path(user), class: 'btn btn-primary', style: 'width: 100%;' do %>
            <div class="clearfix">
              <span class="pull-left"><%= user.name %></span>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<div id="show_modal">
</div>

app/views/chatrooms/new.html.erb
<div class="well">
  <h3 class="text-center">New Channel</h3>
  <% if flash[:error].present? %>
    <div class="alert alert-danger alert-dismissible">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <p><%= flash[:error] %></p>
    </div>
  <% end %>
  <%= form_for(@chatroom, url: chatrooms_path) do |f| %>
    <div class="form-group">
      <%= f.text_field :topic, autofocus: true, class: 'form-control', placeholder: 'Channel Name' %>
      <div class="checkbox">
        <label id="password_field_check_box">
          <%= f.check_box :is_private %> Set Private
        </label>
      </div>
    </div>
    <div class="form-group">
      <%= f.password_field :password, autocomplete: :off, class: 'form-control', placeholder: 'Set Password' %>
    </div>
    <div class="form-group">
      <%= f.submit 'Create Channel', class: 'btn btn-success', style: 'width: 100%;' %>
    </div>
  <% end %>
</div>

app/views/chatrooms/show.html.erb
<% if @chatroom.try(:is_private?) %>
  <% if session[:chatroom_access] == @chatroom.id %>
    <%= render partial: 'chatrooms/open_chatroom', locals: { chatroom: @chatroom, message: @message } %>
  <% else %>
    <%= render partial: 'chatrooms/close_chatroom' %>
  <% end %>
<% else %>
  <%= render partial: 'chatrooms/open_chatroom', locals: { chatroom: @chatroom, message: @message } %>
<% end %>
<div id="show_modal"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= action_cable_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'Chat Awesome', root_path, class: 'navbar-brand' %>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to "Hi, #{current_user.name}", current_user.provider.present? ? nil : edit_user_registration_path  %>
            </li>
            <li>
              <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container" style="margin-top: 20px;">
      <%= render partial: 'shared/alert_messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= action_cable_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<p>
  <b><%= h message.user.name %>: </b>
  <%= h message.body %>
</p>

app/views/messages/_message_form.html.erb
<%= form_for message, remote: true, authenticity_token: true do |f| %>
  <%= f.label :your_message %>:
  <div class="input-group">
    <%= f.text_field :body, class: "form-control", id: "message_field_#{current_user.id}", autocomplete: :off, required: true %>
    <span class="input-group-btn">
      <%= f.submit "Send", class: 'btn btn-success' %>
    </span>
  </div>

  <%= f.hidden_field :chat_id, value: chatroom.id %>
  <%= f.hidden_field :chat_type, value: chatroom.class %>
<%end%>

app/views/private_chats/create.html.erb
<h1>PrivateChats#create</h1>
<p>Find me in app/views/private_chats/create.html.erb</p>

app/views/private_chats/show.html.erb
<h1>PrivateChats#show</h1>
<p>Find me in app/views/private_chats/show.html.erb</p>

app/views/shared/_alert_messages.html.erb
<% if alert %>
  <p class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </p>
<% end %>
<% if notice %>
  <p class="alert alert-info alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </p>
<% end %>